### ISSUE TITLE
Overlapping Text

### ISSUE THREAD

**Issue by djeraseit** [christophery/pushy#100]
Maybe it's my implementation but there seems to be overlapping of text.

Using the example provided, if you put about 25 elements under the first drop down menu, when the drop down menu is expanded, the links of 25 menu elements/links cover over the text of the other links.

**Comment by CHEWX** [comment]
If you could re-produce this on https://jsfiddle.net/ - so we can take a look.

**Comment by asgerv** [comment]
I have the same problem. Created a jsfiddle for it:
[https://jsfiddle.net/8go6zzd4/](https://jsfiddle.net/8go6zzd4/)

**Comment by jamalrahmat** [comment]
Maybe this is the culprit...

`.pushy-submenu-open ul {
  max-height: 1000px;
}`

Modify or delete that class...

**Comment by christophery** [comment]
Yep, if you have too many items in your submenu you'll have to modify the `max-height`. That's the current workaround because you can't animate `height` from `0` to `auto` using CSS.
