### ISSUE TITLE
Not working with wordpress

### ISSUE THREAD

**Issue by mahedimukut** [christophery/pushy#102]
It's working accurately in my HTML project but not working in my WordPress.
HTML website link: http://brahmanbariatimes.com/index.html

**Comment by christophery** [comment]
I've used Pushy in multiple WordPress projects and it works fine. Make sure you are [enqueuing](https://developer.wordpress.org/reference/functions/wp_enqueue_script/) the files correctly and loading jQuery as a dependancy.

What console errors are you getting in the browser?

**Comment by mahedimukut** [comment]
Tx for ur comment christophery. I hv solved the problem. Tx again for ur great plugin.
