### ISSUE TITLE
Menu won't init "Cannot read property 'insertBefore' of null"

### ISSUE THREAD

**Issue by hiphigi** [christophery/pushy#104]
Is this incompatible with jQuery 2+? It keeps throwing this error in a plain fiddle.

https://jsfiddle.net/yh8dmnkg/

**Comment by christophery** [comment]
Can't replicate your issue. [Pushy works fine with jQuery 3.x](https://jsfiddle.net/gndkypa9/)

The error that you're getting is referenced on issue #88 , this is a duplicate issue.
