### ISSUE TITLE
How to control open/close speed

### ISSUE THREAD

**Issue by echolte** [christophery/pushy#105]
How can I control the open/close speed.
I see 'menuSpeed = 200, //jQuery fallback menu speed',
But changing menuSpeed from 200 to any other number has no effect at all.

**Comment by christophery** [comment]
As this comment suggests `//jQuery fallback menu speed`, the `menuSpeed` var is for the jQuery fallback speed. For modern browsers the menu speed is done with CSS transitions.

**Comment by echolte** [comment]
Thank you.
