### ISSUE TITLE
usage of class 'no-csstransforms3d'

### ISSUE THREAD

**Issue by jiangshanmeta** [christophery/pushy#108]
I see you add class 'no-csstransforms3d' to body when the browser doesn`t support transform3d,but there is no usage in CSS. After you add this class to body,you modify the style for the nav,actually you could just use the css to do it.

```
.no-csstransforms3d  .pushy-left{
   left:-200px;
}
.no-csstransforms3d  .pushy-right{
   right:-200px;
}
``` 

As you achive it with css,why use javascript.

Personally,I think you use variable ‘cssTransforms3d’ too separate.For example,you have  function 'closePushy' for closeing pushy when supporting transform3d,and function 'closePushyFallback' for closing pushy when not supporting transform3d,I think you could only have one function and judge whether the browser supporting transform3d in this function.

**Comment by christophery** [comment]
No longer adding that CSS class to body.
