### ISSUE TITLE
Close menu at larger breakpoints

### ISSUE THREAD

**Issue by ottz0** [christophery/pushy#109]
I'm using media queries (Using Bootstrap v4) and am using the pushy menu on the (sm) breakpoint for mobile. When viewed on larger devices I need my regular menu to takeover however pushy just stays toggle open or closed at all break points.

Is there a way to have it responsive(regular menu/pushy menu on mobile)? I have tried hidden however it just hides the css and all I see is a blank portion to the left of my screen.

Breakpoint>544px>push.close()

**Comment by christophery** [comment]
See #7
