### ISSUE TITLE
Pushy doesn`t work with wordpress

### ISSUE THREAD

**Issue by Yaroslav1994** [christophery/pushy#115]
I am tried to combine together  wordpress and pushy, but its doesn`t work.
Pushy.js included in wordpress, i use this code:
```
wp_enqueue_script( 'wp-jquery', get_template_directory_uri() . '/libs/jquery/dist/jquery.min.js' );
wp_enqueue_script( 'wp-pushy', get_template_directory_uri() . '/libs/pushy/js/pushy.js' );
```

Styles are included and work well, but js doesnt work.
In the source code pushy.js is displayed.

**Comment by christophery** [comment]
Pushy works fine with WordPress, I've used it a many times with my WordPress projects.

Here are some tips:

- Use the **console in your browser** to troubleshoot errors in your theme.
- Make sure you are [enqueuing](https://developer.wordpress.org/reference/functions/wp_enqueue_script/) the scripts correctly in your theme.
- Pushy requires **jQuery**, so be sure to load it as a [dependancy](https://developer.wordpress.org/reference/functions/wp_enqueue_script/).
- If you are using [wp_nav_menu](https://developer.wordpress.org/reference/functions/wp_nav_menu/) with Pushy, you will need to use a [Walker](https://codex.wordpress.org/Class_Reference/Walker) to add the CSS classes Pushy requires.

**Comment by Yaroslav1994** [comment]
yes, i solved this issue.
-In the console doesn`t displayed any errors.
-Scripts corectly displayed in theme. I found pushy.js in source code of my theme.(Ctrl +U)
-Jquery is loaded (Before pushy.js).

I solved this issue by putting source code of pushy.js to my main.js file without
`( function ( $ ){ }( jQuery )).`
 It`s work well. I dont know why...

**Comment by christophery** [comment]
Yes, JS in WordPress [needs to be wrapped in an anonymous function](https://digwp.com/2011/09/using-instead-of-jquery-in-wordpress/).

FYI [pushy.js](https://github.com/christophery/pushy/blob/master/js/pushy.js) is already wrapped in an anonymous function, so this wouldn't be an issue including the JS with WordPress

**Comment by amichel86** [comment]
By any chance would you have a walker function already written for this @christophery ? :)
