### ISSUE TITLE
Menu transitions on page load

### ISSUE THREAD

**Issue by amichel86** [christophery/pushy#122]
Hey there, maybe the question has been asked before but I can't find it. Is it normal that when the page loads I see the menu transitions to its closed state? It only happens when the URL is opened from a new tab in Chrome, if I refresh the page this behavior doesn't happen.

URL: http://web.groupearobas.ca/gcp/index.html
Video explaining problem: https://youtu.be/i0bcv3yXR9w

Thanks!

**Comment by christophery** [comment]
I haven't run into that specific issue while using Pushy on my projects.

But I think your issue could be solved by these suggestions in Issue #55

**Comment by amichel86** [comment]
It helps, thanks!
