### ISSUE TITLE
Can width be set to 100%

### ISSUE THREAD

**Issue by mtsweir** [christophery/pushy#123]
Because mobile device widths vary so much, is it possible to set a full width instead of a px value?

**Comment by amichel86** [comment]
From the documentation:

![image](https://user-images.githubusercontent.com/5871701/34010497-f0a9d7fc-e0da-11e7-987d-3394a2f233bf.png)

**Comment by christophery** [comment]
Sure! Setting the width using either percentages or viewport units will work.

Please view the documentation for more information.
