### ISSUE TITLE
Rearrange menu items for desktop

### ISSUE THREAD

**Issue by sheldonkennedy** [christophery/pushy#125]
Love using Pushy, especially the solution of site-overlay instead of wrapping the rest of my content in a div. It would be useful if Pushy opened up into a top bar menu at desktop viewports. I hacked a solution which runs the span and a elements inline, and keeps the container visibile, but the user interaction is not intuitive. If I click a dropdown, I can only collapse it by clicking on the top level item again instead of being able to click away.

**Comment by christophery** [comment]
Thanks for using Pushy, it wasn't designed as a top bar menu on desktop but feel free to modify the source for your own uses.

**Comment by luniawebsites** [comment]
Thanks. I use an adapted version on my sites now. If you want, have a look at https://vfisa.co.za for an example.

**Comment by christophery** [comment]
@luniawebsites Site looks great! 👍
