### ISSUE TITLE
Fit Pushy for container width.

### ISSUE THREAD

**Issue by daranaveen007** [christophery/pushy#126]
![image](https://user-images.githubusercontent.com/23257694/43588144-7ce54418-9689-11e8-8270-d83e75fbad65.png)

I just need to make it look like this for all devices. Please let me suggest what I have to do.

Presently it's stick with edge of left side, but I want it within the container width for all desktops and ipads. For mobiles as it is right now how it is.

Thanks! Waiting for the response.

**Comment by christophery** [comment]
Pushy wasn't intended for this purpose. Pushy needs to be outside of the container for it to work properly.
