### ISSUE TITLE
Change menu-btn class

### ISSUE THREAD

**Issue by mhrabiee** [christophery/pushy#131]
Hi
How can i change 'menu-btn' class for toggling menu? is there option can we pass via js?

**Comment by christophery** [comment]
You can [change the CSS class on line 15](https://github.com/christophery/pushy/blob/e2797ef7c066b231c531bffd7b10b1aee4e35377/js/pushy.js#L15).

**Comment by mhrabiee** [comment]
Thanks.
Any plan for add options via JS? I would open a PR if you are agree.

**Comment by christophery** [comment]
What's your use case for changing the class for toggling the menu?

**Comment by mhrabiee** [comment]
Duplicated class name in my codebase and class naming inconsistency for example.

**Comment by christophery** [comment]
I’ve added this functionality in a [new branch](https://github.com/christophery/pushy/tree/user-defined-menu-btn-class) with the ability to set the menu-btn class via a new **data attribute**.

Check out the [modified demo.html](https://github.com/christophery/pushy/blob/user-defined-menu-btn-class/demo.html#L23) for an example of a custom menu-btn CSS class defined.

It still needs to be tested but this should solve your issue.

**Comment by mhrabiee** [comment]
Great! thanks.
