### ISSUE TITLE
Error don't appear the pushy menu

### ISSUE THREAD

**Issue by marcelomaeda** [christophery/pushy#134]
Hi,

I am testing the pushy menu

It works in some pages but does not work on this page: http://shoptest1mob.mformula.info/fashion-tops-avalon-shirt-p-215.html

I appreciate any help to solve this problem.

Thank you
Best regards

**Comment by christophery** [comment]
It looks like you are loading jQuery twice on that page:

<img width="490" alt="Screen Shot 2019-11-20 at 9 55 36 AM" src="https://user-images.githubusercontent.com/1683361/69249620-2bfbe480-0b7c-11ea-898b-7ef18603fb25.png">

jQuery only needs to be included once on your page. I recommend using the **Network** panel in Chrome/Firefox Developer Tools to locate your duplicate jQuery script.
