### ISSUE TITLE
Mobile Site Menu is not loading properly

### ISSUE THREAD

**Issue by Natesilvey** [christophery/pushy#137]
The mobile site menu is stuck overlapping each item. 

see here: https://www.meadowlarkbuilders.com/

Would appreciate help.

Thanks

**Comment by Natesilvey** [comment]
Any update on this?

**Comment by christophery** [comment]
You are missing required classes + markup. 

You need to wrap `.pushy-content` with the required `.pushy` class, please refer to the [documentation](https://github.com/christophery/pushy#install).
