### ISSUE TITLE
Save a network request by encoding the arrow svg in the css instead of externally linking it

### ISSUE THREAD

**Issue by hadithmv** [christophery/pushy#139]
Hi @christophery 

Instead of this:
```
.pushy-submenu > a::after,
.pushy-submenu > button::after {
  background: url("../img/arrow.svg") no-repeat;
```
  
  How about using **this**:
```
    background: url("data:image/svg+xml,%3Csvg id='arrow' xmlns='http://www.w3.org/2000/svg' width='7.9' height='10.9' viewBox='0 0 7.9 10.9'%3E%3Ctitle%3Earrow%3C/title%3E%3Cpath id='arrow' data-name='arrow' d='M8,5.5 L1.9,11,0.1,9.4,4.4,5.6,0.1,1.8,2,0.1,8,5.5' transform='' fill='%23b3b3b1'/%3E%3C/svg%3E")
    no-repeat;
```
    
Of course if anyone doesn't need this arrow for submenus, they could just comment it out in the css code.

**Comment by christophery** [comment]
I originally thought about inlining the SVG but decided against it because it's much easier + quicker to replace an external SVG file. 

If people want to save a network request they can inline the file themselves.
