### ISSUE TITLE
Menu visible by default

### ISSUE THREAD

**Issue by jondlm** [christophery/pushy#17]
From how I understand it, the pushy menu is visible by default (on non-3d transform browsers) until the javascript is loaded and it's hidden. It would be better to include some class in the css that assigns `display:none` that is removed once the javascript is loaded properly. This would prevent the menu from showing up on non-javascript, or blocked javascript, browsers. I've got a solution working, but I wanted to see if you're interested before I submit a PR.

**Comment by christophery** [comment]
Fixed with #80.
