### ISSUE TITLE
Switch position pushy menu

### ISSUE THREAD

**Issue by Caspert** [christophery/pushy#25]
Great plugin! One question, how can I switch from a left menu to the right menu. So it toggles out of the right?

Thnkx!

**Comment by Antrikshy** [comment]
To those who stumble upon this question in the future, I've got your back with full instructions here: http://blog.antrikshy.com/make-pushy-off-canvas-menu-appear-from-the-right/

**Comment by Agressiva86** [comment]
@christophery thanks :) You saved my day :)

**Comment by christophery** [comment]
Pushy now supports left or right menu position.

**Comment by jk-1984** [comment]
Hi sorry if this is a old post but i have just found your awesome menu.
I would just like to know if i can set the menu open when the page is loaded?
I am very new to code so any help would be appreciated.

Thank you.
