### ISSUE TITLE
Don't display menu until JS has loaded

### ISSUE THREAD

**Issue by sprklp** [christophery/pushy#27]
Hi there! I love Pushy, it's a fantastic solution, thank you for sharing it and I really hope you keep developing it further. I was wondering if there is any way I can attach a  ```display:none; ``` class to stop the menu flashing up on page load before it is hidden, then change this to a class of  ```display:block; ``` when the page has loaded? 

Currently giving the nav an id to ``` display:none; ``` and when  ```.pushy-active ``` is passed to  ```display: block; ```, this works but loses css transitions (nav pops up/disappears instantly when trigger button is clicked). 

Nav flashes up on IE8+9 (in browserstack) but not so prevalent on other browsers. Curiously, this issue happens in downloadable demo version of Pushy but not your live demo here http://www.christopheryee.ca/pushy/. Thanks for any info!

**Comment by christophery** [comment]
Fixed with #80
