### ISSUE TITLE
Breaks html5 video on Chrome on Android

### ISSUE THREAD

**Issue by rashidalnaemi** [christophery/pushy#38]
When using pushy. HTML5 videos on Android play, but the controls disappear when they're in full screen. I've narrowed it down to pushy.

When I remove pushy, everything works fine.

If pushy is active, then the control bar for the video appears somewhere in the middle of the screen (if at all) but touching that does nothing. Interacting with it still occurs at the bottom of the screen (where there's nothing visible)

**Comment by christophery** [comment]
I haven't encountered this issue in my projects while using Pushy. Can't reproduce this issue.
