### ISSUE TITLE
Compatibility Issue with Sticky.js?

### ISSUE THREAD

**Issue by ericjacksonwood** [christophery/pushy#49]
I'm using sticky.js to fix my header to the top of the window at all times, which seems to be working fine. Then I added pushy.js to add the off-canvas menu function, and it seemed at first to be working as well.

If you're at the very top of the page (before sticky.js kicks in) and you click the .menu-btn - the whole page (header included) slides over, and the nav menu fills in that space (using pushy.js). However, if you scroll down the page (after sticky.js has forced the header to remain visible) and click the .menu-btn - the header shoots right back to the top of the page (as if sticky.js is being disabled). If you close the menu, the site slides back over and the sticky-header appear suddenly (which really makes for a laggy experience).

There are no stylesheets for the Sticky.js plugin and I haven't changed anything from the original Pushy.js stylesheet, so I looked to see if there was anything contradicting it in my CSS, but I couldn't seem to find the issue:

```
.header {
    border-top: 1em solid #69c7c8;
    background-color: #fff;
    padding: 2em 0;
    width: 100%;
    position: absolute;
    z-index: 999999;
}
```

Have you ever worked with sticky.js before while using this plugin?

**Comment by Overtrainer** [comment]
have a same problem, but without sticky.js, just jquery code:
`$(window).scroll(function() {
        if ($(this).scrollTop() > 63) {
            $('header').addClass("sticky");
        } else {
            $('header').removeClass("sticky");
        }
    });`
if you found or will find solution, please share it :)

**Comment by vtxmg** [comment]
+1
