### ISSUE TITLE
Fixed menu at top?

### ISSUE THREAD

**Issue by emage** [christophery/pushy#5]
Can you add this feature?  On mobile scrolling long content the menu icon is gone and you have to scroll a loooooong way up to access the menu agian.

thanks

**Comment by strigga** [comment]
i have a fixed menu bar on top of page. if the user clicks on the menu button and the pushy menu moves into window the fixed menu bar isn't fixed. after closing the menu it is fixed again. is there a solution for this problem?

**Comment by CreativityKills** [comment]
What @strigga said

**Comment by mreee** [comment]
Pretty delayed on the reply here but 
`-webkit-perspective: 1000;`

Can cause issues with fixed positioning. Try adding:
`#container { -webkit-perspective: none; }`
