### ISSUE TITLE
HTML element for triple bars is broken in some browsers

### ISSUE THREAD

**Issue by jsmad** [christophery/pushy#54]
The example HTML code uses &#9776; to display the triple bars (mobile icon) to open the pushy menu. Unfortunately, this HTML code does not always work. For example, it is broken on WinXP with Chrome and Opera.

If you look at the sites listed as using pushy, you'll see how most of them have stopped using this HTML code and instead use font symbols (like font-awesome).

It may be worth investing some time to find a better replacement that works on all/most platforms.

**Comment by jsmad** [comment]
Oh, I forgot to mention that my solution is to use:

```
&equiv;
```

But I have to raise the font-size and lower the line-height, to get it to align properly.

**Comment by christophery** [comment]
I don't expect people to use the HTML triple bars icon in the demo (it's for example/demo only), it's intended and implied that the user will replace it with either a icon font or SVG of their choosing.

FYI I don't support and/or test in Windows XP anymore, not really a huge issue IMO.
