### ISSUE TITLE
Visible when zooming-in

### ISSUE THREAD

**Issue by gabrielconstantin** [christophery/pushy#55]
The menu (that should be in hidden state) comes into view briefly when zooming-in the browser. The transition of the transformation is the source of the issue but I couldn't find a solution yet.

**Comment by christophery** [comment]
You could potentially hide pushy with `opacity: 0` and when Pushy is open set it to `opacity: 1`, plus you would need to add the `opacity` property to the menu transitions class. This would fix the issue with Pushy showing (briefly) when zooming in the browser. 

The only downside to this addition would be that when the menu is closed the animation/effect looks slightly different than intended.

**Comment by gabrielconstantin** [comment]
Thank you @christophery ! I already implemented the exact same thing, just .1s for the opacity transition, so x3 faster than the transform, both on the same cubic-bezier function. I actually like the effect, so no downside really. 

I've seen the default pushy implementation on other sites and I personally consider the brief visibility of the otherwise off canvas navigation to be a bug.
