### ISSUE TITLE
Menu not showing when using jQuery Fallbacks

### ISSUE THREAD

**Issue by philgyford** [christophery/pushy#60]
If I make my browser (Chrome) use the jQuery fallbacks, instead of CSS transitions, the menu doesn't appear when the content slides to the right.

I fixed this by changing [this line](https://github.com/christophery/pushy/blob/master/js/pushy.js#L29) from this:

    pushy.animate({left: "0px"}, menuSpeed);

to this:

    pushy.animate({left: menuWidth}, menuSpeed);

I'm not sure why that works - I thought 0px would be fine - but it seems to.

**Comment by rwong48** [comment]
Thanks! Almost opened an issue myself, but found this. Here are fiddles demonstrating the issue.

Before (stock Pushy, but changed `if (cssTransforms3d)` to `if (false)`) : http://jsfiddle.net/nn0zLke5/
After your patch: http://jsfiddle.net/nn0zLke5/1/

**Comment by christophery** [comment]
Fixed in #80
