### ISSUE TITLE
Disable close menu on link click

### ISSUE THREAD

**Issue by markcy** [christophery/pushy#61]
How can I make it so when a link in my menu is clicked, pushy does not slide away?  I'm adding an accordion sub menu system, and the parent menu items are a tags by default in WordPress.  So when I click it to open my accordion, pushy closes.

How can I edit the push js file to remove this functionality?  

I figure, when you click a link in the menu, the page is going to reload anyway in most cases, so I don't need it to auto close the pushy menu.

Thanks.

**Comment by christophery** [comment]
Change [Line 16](https://github.com/christophery/pushy/blob/master/js/pushy.js#L16) in the JS file. This line specifies which CSS classes will toggle the menu.

Easy!

**Comment by pastullo** [comment]
Great, thanks!

**Comment by applesapples1** [comment]
I followed the above instructions and it worked to stop the navbar from closing, however the links in the accordion stopped working. Can you please help with this?
