### ISSUE TITLE
Block scrolling on #container when menu is open

### ISSUE THREAD

**Issue by rwong48** [christophery/pushy#62]
We shouldn't be able to scroll the main content while our menu is open.

This reproduces with `demo.html` in the source repo, but doesn't reproduce on http://www.christopheryee.ca/pushy/.

**Comment by christophery** [comment]
FYI it's in the [read me under tips](https://github.com/christophery/pushy/blob/master/README.md#tips).

**Comment by EvilJordan** [comment]
This doesn't work. Visit your site on any iPhone.
