### ISSUE TITLE
many different status classes

### ISSUE THREAD

**Issue by nicmare** [christophery/pushy#63]
is there a special reason to have many different status classes?
.pushy-open, .pushy-active, .container-push, .push-push

why not simply apply ONE "pushy-active" class to html element and apply all styles:

.pushy-active body {
// overflow:hidden
}
.pushy-active .pushy {
// pushy is open
}
.pushy-active #container {
// push the container
}
and so on…
i think you could save some lines of code! because of just need to toggle one class.

**Comment by christophery** [comment]
Consolidated menu state CSS classes. See #80.
