### ISSUE TITLE
Drop downs in menu

### ISSUE THREAD

**Issue by mtsweir** [christophery/pushy#65]
Can it be possible to have a drop down nav display in the off canvas nav? When opened I would like to add a multi-level drop down. But when on desktop I click anything in the menu it closes by default.
I would also like to trigger the close with a link too e.g

off canvas menu:
close button
main nav

**Comment by mtsweir** [comment]
Found a solution that works for me, changed the default classes for toggling off canvas to my custom classes e.g menuBtn = $('.menu-btn, .button-close')

**Comment by christophery** [comment]
Pushy now has auto-collapsable submenus. Only links with the CSS class of ```pushy-link``` will close the menu.
