### ISSUE TITLE
IPad & IPhone problem

### ISSUE THREAD

**Issue by Avatar4eg** [christophery/pushy#66]
On ios ive got this problem (screenshots) - pushy somehow stuck over part of screen (on the left) and doesnt answer to any click.
But in chrome on this screens emulations it behaves perfect. 
I have no idea whats wrong :C

![chrome](https://cloud.githubusercontent.com/assets/2990059/9382850/d430cede-474c-11e5-9c7f-05f07b9a1243.PNG)
![ipad](https://cloud.githubusercontent.com/assets/2990059/9382849/d42d9476-474c-11e5-93a4-3b07d97a35d4.PNG)

**Comment by christophery** [comment]
The demo seems to be working fine on my iPad 2 running iOS 8 and in the iOS simulator.
