### ISSUE TITLE
Pushy menu partly visible on Android 4.2 Browser

### ISSUE THREAD

**Issue by mschilder** [christophery/pushy#67]
Hi! I'm a happy user of pushy nav. But I found out that on the native Android 4.2 (4.2.2 Jelly Bean) Browser (and presumably also Android 4.1) somehow the pushynav stays partly visible (see screens attached). 

The only way to prevent this from happening seems to be adding .pushy-left { left: -200px } for Android4 devices. 

Any ideas to prevent this from happening and/or fix this in the core of pushy?

![screenshot_2015-08-16-15-59-04](https://cloud.githubusercontent.com/assets/1308968/9440117/f1141e48-4a6c-11e5-8d73-12bf3d9a01f1.png)
![screenshot_2015-08-18-10-56-25](https://cloud.githubusercontent.com/assets/1308968/9440118/f131c3d0-4a6c-11e5-94fd-47db713c2ea3.png)

**Comment by christophery** [comment]
Can't reproduce this issue on my Android tablet with the generic "Internet" browser or my Nexus 5 running Chrome.
