### ISSUE TITLE
When i increase the width of side panel + sign does't show in android phone. But when i touched it start showing.

### ISSUE THREAD

**Issue by sumitebizon** [christophery/pushy#72]
When i increase the width of side panel + sign does't show in android phone. But when i touched it start showing.

**Comment by sumitebizon** [comment]
![screenshot_2015-09-22-16-25-00 1](https://cloud.githubusercontent.com/assets/14760732/10016725/c09e9130-6146-11e5-9672-864ed3ba1f76.png)

**Comment by christophery** [comment]
Can't reproduce this issue on my Android tablet with the generic "Internet" browser or my Nexus 5 running Chrome.
