### ISSUE TITLE
menu shrinking in latest safari browser

### ISSUE THREAD

**Issue by eddiemilla** [christophery/pushy#73]
i just downloaded latest iphone OS and now the menu is 'shrinking' in the browser window.
is there a fix?
(its not happening on chrome for iphone).
please advise.
e milla

**Comment by bigmikestudios** [comment]
I had a similar issue, I found adding "shrink-to-fit=no" to the viewport meta tag fixed it for me.

`<meta name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1, min-scale=1, max-scale=1">`

**Comment by christophery** [comment]
I can't replicate this issue on my iPhone running iOS 9.
