### ISSUE TITLE
Pushy for already existing menus

### ISSUE THREAD

**Issue by ivansieder** [christophery/pushy#74]
It should be possible, that pushy adapts to already existing menus with a similar structure like:

```html
<nav class="menu">
    <ul>
        <li>...</li>
        <li>...</li>
    </ul>
</nav>
```

**Comment by jenstornell** [comment]
"pussy", haha! It's name is Pushy!

**Comment by ivansieder** [comment]
Whoops that was a typo @jenstornell ^^ Thanks for mentioning it

**Comment by christophery** [comment]
Pushy does work with that exact DOM structure, all you need to add ```pushy``` + ```pushy-left``` CSS classes.
