### ISSUE TITLE
What about multi level menu ? 

### ISSUE THREAD

**Issue by designinsist** [christophery/pushy#76]
I have many parent menu items and every parent have some child. The issue that your plug in treat all the items items in the same way. what i want that the sub child elements look like or behave like accordion.
This make sense or i have to show you any example ?
This is possible with the plug in ? 
Other wise this plug in perfect and i like it a lot.
Looking forward to hear from you :)
Many many thanks.

**Comment by designinsist** [comment]
For your help this is the mark up.
<ul>
       <li>
               <ul>
               </ul>
       </li>
</ul>

**Comment by sertaconay** [comment]
See #61

**Comment by christophery** [comment]
Pushy now has auto-collapsable submenus.
