### ISSUE TITLE
Menu not working

### ISSUE THREAD

**Issue by xann1891** [christophery/pushy#79]
I found your Pushy code and was intrigued because it is exactly what I had been looking for when redesigning my website.  I have followed all the instructions, and have looked at several of the sample websites, but I am still having a problem with my page.

What I want the menu to do is be a horizontal menu when it is in Desktop format and then convert over to the Pushy Menu when it is in Tablet or Mobile size.  Right now, that is not happening.  I also want the Menu button to be hidden on the Desktop view.  Right now the Menu button does not appear to be a button at all and is currently visible in all views; also the menu button is not behaving as a button
 
Any suggestions would be helpful.

The preliminary page can be seen at http://footcandles.net/index-test.php

UPDATE:  I discovered I was missing some css code.  After adding the code, my menu button is now registering as a button, but it still is not triggering the pushy menu when clicked.

**Comment by xann1891** [comment]
UPDATE:  I discovered I was missing some css code.  After adding the code, my menu button is now registering as a button, but it still is not triggering the pushy menu when clicked.  Also, still trying to figure out how to view the menu a horizontal menu when in Desktop and as the Pushy Menu when in Tablet and Mobile.

**Comment by christophery** [comment]
It might help if you fix those errors in the console. It looks like you're not loading the JS file, this file is required for the menu to work properly.
