### ISSUE TITLE
Autoprefixer in the gruntfile

### ISSUE THREAD

**Issue by DrChills** [christophery/pushy#81]
It seems the .css file wasn't including prefixes - which meant the animation wasn't great (or working, actually)

So i've added:
Package.json:
```
  "devDependencies": {
    "grunt": "~0.4.4",
    "grunt-autoprefixer": "^3.0.4",
    "grunt-contrib-concat": "~0.4.0",
    "grunt-contrib-sass": "~0.9.2",
    "grunt-contrib-uglify": "~0.4.0",
    "grunt-contrib-watch": "~0.6.1"
  }
```
gruntfile:
```
autoprefixer: {
      main: {
        expand: true,
        flatten: true,
        src: 'css/*.css',
        dest: '/'
      }
    }
```

(register the task)
`  grunt.loadNpmTasks('grunt-autoprefixer');`

and finally edited the sass task:

```
  css: {
        files: ['scss/*.scss'],
        tasks: ['sass-task', 'autoprefixer'],
      },
```

**Comment by christophery** [comment]
It appears the CSS does contain the necessary vendor prefixes for modern browsers. Which properties are missing prefixes?
