### ISSUE TITLE
Submenu Parent Anchor Link triggers submenu to open, while also clicking and going to the next page.

### ISSUE THREAD

**Issue by martindefatte** [christophery/pushy#83]
I think it would be a better UX if the arrows ( .pushy-submenu > a::after ) could be clickable, but not cause the anchor it's appended after to be triggered. When clicking on the arrow, you briefly see the submenu open before the browser loads page you've just clicked. I still want my top level navigation to be useable, rather than simply being buttons for the submenu items. When these top levels have actual links, the submenus are not able to be clicked on.

Also, it seems that the "submenuClass" variable set in line 18 is also hardcoded in lines 94 and 98. It would be easier to deploy if the variables were set throughout the code.

**Comment by martindefatte** [comment]
I had to alter this line, in order to actually kill the loading of the new page. I still need to figure out a way to allow the arrow to open the submenu, and the link to click to the next page.
`function toggleSubmenu(){
		//hide submenu by default
		$(submenuClass).addClass(submenuClosedClass);

		$(submenuClass).on('click', function(){
	        var selected = $(this);
			event.preventDefault(); // added by martindefatte
	        if( selected.hasClass(submenuClosedClass) ) {
	            //hide opened submenus
	            $(submenuClass).addClass(submenuClosedClass).removeClass(submenuOpenClass);
	            //show submenu
	            selected.removeClass(submenuClosedClass).addClass(submenuOpenClass);
	        }else{
	            //hide submenu
	            selected.addClass(submenuClosedClass).removeClass(submenuOpenClass);
	        }
	    });
	}`

**Comment by vdecree** [comment]
Agreed. I've only just caught this one a site that I've tried using Pushy on. My dropdown is unacessible at it stands

**Comment by christophery** [comment]
I don't think this is good UX, I don't like the idea of confusing the user with a button that performs two different actions (link + open submenu). I'd rather have one predictable action (open submenu) that has a nice large touch/hit area for the user.

You're free to modify the script to accomplish this functionality. The hard coded class is no longer an issue with the latest release of Pushy.
