### ISSUE TITLE
Add support for settings $menu_width without changing source

### ISSUE THREAD

**Issue by erzki** [christophery/pushy#84]
Hi

After downloading pushy from bower I don't want to change the puschy.scss. Can you change the code below. It will the be possible to set $menu_width in my own sass code.
$menu_width: 200px;

to

@if ($menu_width == null) {
    $menu_width: 200px;
}

**Comment by Saboteur777** [comment]
Or you can simply modify 
`$menu_width: 200px;`
to 
`$menu_width: 200px !default;`

[source](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#variable_defaults_)

**Comment by christophery** [comment]
Fixed with #89
