### ISSUE TITLE
Is it possible to trigger the open and close behaviors

### ISSUE THREAD

**Issue by ecurtis** [christophery/pushy#9]
I would like to call the open and close functions from outside the script, would that be possible?

**Comment by Cam** [comment]
+1 Can we have a close class built in?

**Comment by mtsweir** [comment]
That would be great to be able to trigger this separately.

**Comment by christophery** [comment]
You can do this easily by adding/removing either the ```pushy-open-left``` or ```pushy-open-right``` CSS class to the body. The CSS class will depend on the menu position that you prefer.
