### ISSUE TITLE
Allow SCSS varibles to overwrite

### ISSUE THREAD

**Issue by CHEWX** [christophery/pushy#92]
Hi,

When using bower to install, I directly include the SCSS partial into my main.scss file.

This allows me to update via bower without copying and pasting, however the varibles is set without a `!default` flag, so it cannot be set before the `@import` delcaration.

Can we change `$menu_width: 200px;` to `$menu_width: 200px !default;`

I would do a pull request but seems pointless for a small request.

Thanks,
Tom

**Comment by christophery** [comment]
Fixed with #89
