### ISSUE TITLE
Hi, I'm a member of cdnjs.

### ISSUE THREAD

**Issue by x09326** [christophery/pushy#99]
Hi, I'm going to host this lib on [cdnjs](https://cdnjs.com).

But I need to confirm which file I should add.
Could you help me?

Thank you for your help.
https://github.com/cdnjs/cdnjs/issues/8301

**Comment by christophery** [comment]
You should add [pushy.min.js](https://github.com/christophery/pushy/blob/master/js/pushy.min.js) and [pushy.css](https://github.com/christophery/pushy/blob/master/css/pushy.css). Both of these files are required for pushy to function.

**Comment by christophery** [comment]
Closed due to lack of activity.
